{% set name = "PyPackIT-Test1" %}
{% set version = "0.0.12" %}
{% set pkg_dir = "./" %}

package:
  name: '{{ name | lower }}'
  version: '{{ version }}'

source:
  path: ../../../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install {{ pkg_dir }} --no-deps --no-build-isolation -vv
  number: 0
  entry_points:
    - PyPackIT-Test1 = pypackit_test1.__main__:main

requirements:
  host:
    - python >=3.10
    - pip
    - conda-forge::setuptools >=72.1.0
    - conda-forge::versioningit >=3.1.2
  run:
    - python >=3.10
    - repodynamics::pkgdata

test:
  imports:
    - pypackit_test1
  requires:
    - pip
  commands:
    - pip check
    - PyPackIT-Test1 --help

about:
  home: https://AAriam.github.io/PyPackIT-Test1
  license: MIT
  license_file:
    - '{{ pkg_dir }}LICENSES/'
  summary: A New Python Project
  dev_url: https://github.com/AAriam/PyPackIT-Test1
  doc_url: https://AAriam.github.io/PyPackIT-Test1
  doc_source_url: https://github.com/AAriam/PyPackIT-Test1/blob/main/pkg/README.md
  description: |-
    {{
      load_file_regex(
        load_file=pkg_dir ~ "README.md",
        regex_pattern="(?s)^(.*)$",
      )[1] | default("") | indent(width=4)
    }}

recipe-maintainers:
  - AAriam
